name: slide
channels:
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_h77c792f_102
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fvcore=0.1.5.post20220512=pyhd8ed1ab_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - igl=2.2.1=py38h52fb889_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=pyhd8ed1ab_0
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py38h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.2=py38h06a4308_0
  - matplotlib-base=3.5.2=py38hf590b9c_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py38h807cd23_0
  - numpy=1.23.1=py38h6c91a56_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py38h6a678d5_0
  - pcre=8.45=h295c915_0
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.2.2=py38h06a4308_0
  - ply=3.11=py38_0
  - portalocker=2.5.1=py38h578d9bd_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyntcloud=0.3.1=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.0=py38_cu113_pyt1121
  - pytz=2022.4=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - scipy=1.9.1=py38h14f4228_0
  - setuptools=63.4.1=py38h06a4308_0
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - termcolor=2.0.1=pyhd8ed1ab_1
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchvision=0.13.1=py38_cu113
  - tornado=6.2=py38h5eee18b_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - trimesh=3.15.3=pyh1a96a4e_0
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.11=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - attrs==22.1.0
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - boto3==1.24.89
    - botocore==1.27.89
    - cachetools==5.2.0
    - coloredlogs==15.0.1
    - cython==0.29.32
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - environs==9.5.0
    - executing==1.1.1
    - fastjsonschema==2.16.2
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - humanfriendly==10.0
    - humanize==4.4.0
    - imageio==2.22.1
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - ipykernel==6.16.0
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - json5==0.9.10
    - jsonschema==4.16.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyter-packaging==0.12.3
    - jupyter-server==1.19.1
    - jupyterlab==3.4.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.2
    - jupyterlab-widgets==3.0.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - marshmallow==3.18.0
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - multiprocessing-logging==0.3.3
    - nbclassic==0.4.5
    - nbclient==0.7.0
    - nbconvert==7.2.1
    - nbformat==5.6.1
    - nest-asyncio==1.5.6
    - networkx==2.8.7
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - oauthlib==3.2.1
    - open3d==0.13.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - plyfile==0.7.4
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.31
    - protobuf==3.19.6
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.13.0
    - pyrsistent==0.18.1
    - python-dotenv==0.21.0
    - pywavelets==1.4.1
    - pyzmq==24.0.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - s3transfer==0.6.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.5.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.16.0
    - threadpoolctl==3.1.0
    - tifffile==2022.8.12
    - tinycss2==1.1.1
    - tomli==2.0.1
    - tomlkit==0.11.5
    - traitlets==5.4.0
    - transforms3d==0.4.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - zipp==3.9.0
